### ISSUE TITLE
link to iron-icons broken

### ISSUE THREAD

**Issue by davidmaxwaterman** [PolymerElements/iron-icon#100]
### Description
The iron-icon demo references the iron-icons demo, but links using the following URL :

/elements/iron-icons?view=demo:demo/index.html

### Expected outcome
Should probably link to :

/PolymerElements/iron-icons/v1.2.0/iron-icons/demo/index.html

(which seems to work when I edit the anchor) or something.

### Actual outcome

404

**Comment by bicknellr** [comment]
Should be fixed by #106.
