### ISSUE TITLE
Mention polyserve

### ISSUE THREAD

**Issue by choskim** [PolymerElements/iron-icon#11]
I think this repository--similar to most of the other repositories--should mention polyserve. Anyone new to Polymer and interested in loading `demo/index.html` most likely will confront two problems: 
1) They will receive errors that the imported HTML files are not found. 
2) They will change the values of the hrefs and then receives a CORS error.

**Comment by ebidel** [comment]
Thanks for the suggestion. I think we should mention polyserve on the polymer documentation (under tools)...which is the POR. This isn't the right place for this request though. This repo is for the iron-icon element features/bugs.
