### ISSUE TITLE
Move template to js

### ISSUE THREAD

**Issue by Punk-UnDeaD** [PolymerElements/iron-icon#113]
What about move all <template> to _template.
If this is done for all components and application builded to one js file, firefox has badass improve performance.

**Comment by notwaldorf** [comment]
This is not how Polymer Elements are written -- one of the biggest pluses of Polymer is that you can write your template in html. If you want to write everything in JS, maybe look at something like lit-html? https://github.com/PolymerLabs/lit-html

**Comment by Punk-UnDeaD** [comment]
Do you hate Firefox users and web-depelopers so much that you think that they should suffer for the sake of the standart?

**Comment by notwaldorf** [comment]
A couple of things. First, Polymer is a library, not a standard. This has nothing to do with Web Components (a standard) but the correct way to write a Polymer element (with the library). 
 1. `_template` is a private variable used by Polymer in caching the template for an element. However, Polymer usually does work before saving the template in there (for styling and data binding) so saving it directly makes no sense. Saving it as a string directly is not even supported in Polymer 1 nor Polymer 2, so I'm not even sure why you think this works.
2. This element is a hybrid element, which means it needs to use in _both_ Polymer 1 and 2. Polymer 1 is ES5 compatible, and you're using backwards quotes, which means this would 100% break the usage of that element in Polymer 1 apps.
3. Saving the template as a string this way has absolutely no performance implications, despite what you might think. From the string, you still have to construct the DOM if you want to stamp it, which Polymer automatically does (when it fetches the template from the `<template>` tag)
