### ISSUE TITLE
Where can I find API docs

### ISSUE THREAD

**Issue by tomalec** [PolymerElements/iron-icon#117]
### Description

Github page links to https://www.webcomponents.org/element/PolymerElements/iron-icon

### Expected outcome
I would like to see API  described, like attribute I can set, their default values and behavior.

### Actual outcome
There is no such thing.

### Live Demo

https://www.webcomponents.org/element/PolymerElements/iron-icon

### Steps to reproduce

1. Open https://github.com/PolymerElements/iron-icon,
2. Open https://www.webcomponents.org/element/PolymerElements/iron-icon

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by notwaldorf** [comment]
If you click on `iron-icon` in the "Elements" section, you get to the docs: https://www.webcomponents.org/element/PolymerElements/iron-icon/elements/iron-icon
