### ISSUE TITLE
The link to the iron-icons demo is dead and not working

### ISSUE THREAD

**Issue by bvhme** [PolymerElements/iron-icon#27]
Is there anywhere where we can get an overview of all icons except for the 0.5 version of this?

Thanks

**Comment by ianchildress** [comment]
Where can we find what icons are included in iron-icon?

**Comment by ghost** [comment]
Hey Guys, 

So I couldn't find it either. I ended up using this: https://www.polymer-project.org/0.5/components/core-icons/demo.html. I just included the core-icons keyword after the iron-icons name. For example, 
"iron-icon icon="work"></iron-icon."

Pretty gangsta and duct-taped, but its a temporary fix. I believe the guys figured out some work around. 
You can read about it here: https://github.com/PolymerElements/iron-icons/issues/13

<b>Note:</b> There is a difference between iron-icon vs. iron-icons.

**Comment by fxedel** [comment]
iron-icon is something different than iron-icons. For this issue, see https://github.com/PolymerElements/iron-icons/issues/21

**Comment by samccone** [comment]
![screen shot 2015-09-16 at 9 39 47 pm](https://cloud.githubusercontent.com/assets/883126/9925071/810b9822-5cbb-11e5-804a-74cd443010f6.png)

https://elements.polymer-project.org/elements/iron-icons?view=demo:demo/index.html

:sparkles: all icons :)

**Comment by arthurevans** [comment]
This isn't working correctly ATM -- if you click the link for the iron-icons demo, you end up with two left nav panels.
