### ISSUE TITLE
How do you set the svg viewBox of a icon?

### ISSUE THREAD

**Issue by gertcuykens** [PolymerElements/iron-icon#28]
I have a 75px viewbox designed icon and need to set the viewbox to 75 instead of 24 else you only see part of the icon in the (24x24) box and yes I tried fiddling with this
`<iron-iconset-svg name="gender-icons" icon-size="75">`
Anyway this should be the result and I can only achieve it with the chrome inspector en edit the viewbox
![image](https://cloud.githubusercontent.com/assets/863731/8295417/bf36d978-1944-11e5-88a0-c72e4d6deb37.png)
Node it has nothing to do with the size of the icon as you can see (24x24) is fine its the viewbox that needs to be changed only.

**Comment by notwaldorf** [comment]
`iron-icon` has two custom properties, `--iron-icon-width` and `--iron-icon-height` that you can use to set the size:

```
iron-icon {
    --iron-icon-width: 40px;
    --iron-icon-height: 24px;
}
```

(As a side note, even if `iconSize` would have been a property, it should have been `icon-size` since it's being used as an html attribute)

**Comment by gertcuykens** [comment]
I dont need to change the size just the svg viewbox inside iron-icon. Wait I will make another picture to make it more clear wat happens if the viewbox is set to the same size als the icon itself

**Comment by gertcuykens** [comment]
![image](https://cloud.githubusercontent.com/assets/863731/8319313/a766d518-1a0d-11e5-9139-78453f459c94.png)

![image](https://cloud.githubusercontent.com/assets/863731/8319321/c77a8962-1a0d-11e5-82dc-cae28fccc777.png)

Notice that the size is in both cases 24x24 I only edited the viewbox in the inspector.

Let me know if it is clear or if I need to make a demo

**Comment by gertcuykens** [comment]
PS I changed it to `<iron-iconset-svg name="gender-icons" icon-size="75">` but it does not affect the viewBox :) If it did then I would have slapped my forehead again for sure :)

Could it be it used to be a property in 0.5 at some point?

**Comment by notwaldorf** [comment]
I don't think this was ever possible, but I'll let @cdata chime in since he knows most about the icons.

**Comment by gertcuykens** [comment]
this is the icon I am talking about

``` html
<iron-iconset-svg name="gender-icons" icon-size="75">
  <svg viewBox="0 0 75 75">
    <defs>

        <g id="female" transform="translate(-348.7552,-478.0905)">
            <g id="g3773" transform="matrix(1.071197,0,0,1.075147,-13.30677,-36.99488)">
              <path
                 d="M 176 33 A 11 11 0 1 1  154,33 A 11 11 0 1 1  176 33 z"
                 transform="matrix(1.540096,0,0,1.5384,118.8893,454.0543)"
                 style="color:black;fill:none;fill-opacity:1;fill-rule:evenodd;stroke:black;stroke-width:3;stroke-linecap:butt;stroke-linejoin:miter;marker:none;marker-start:none;marker-mid:none;marker-end:none;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1;visibility:visible;display:inline;overflow:visible"
                 id="path3939" />
              <path
                 d="M 373.00525,521.74399 L 373.00525,543.28159"
                 style="fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:black;stroke-width:4.61774349;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
                 id="path3941" />
              <path
                 d="M 363.76467,534.05119 L 382.24582,534.05119"
                 style="fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:black;stroke-width:4.61774349;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
                 id="path4816" />
            </g>
        </g>

        <g id="male" transform="translate(-348.7552,-478.0905)">
            <g id="g1872" transform="matrix(1.948116,0,0,1.937312,-342.4303,-460.0101)">
              <path
                 d="M 387.95009,489.60348 L 378.66214,498.89143"
                 style="opacity:1;color:black;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:black;stroke-width:3;stroke-linecap:butt;stroke-linejoin:miter;marker:none;marker-start:none;marker-mid:none;marker-end:none;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1;visibility:visible;display:inline;overflow:visible"
                 id="path26867" />
              <path
                 d="M 49.396475 36.70454 A 15.623922 16.319134 0 1 1  18.14863,36.70454 A 15.623922 16.319134 0 1 1  49.396475 36.70454 z"
                 transform="matrix(0.48802,0.48802,-0.467594,0.467594,371.6094,473.1357)"
                 style="opacity:1;color:black;fill:none;fill-opacity:1;fill-rule:evenodd;stroke:black;stroke-width:4.44071579;stroke-linecap:butt;stroke-linejoin:miter;marker:none;marker-start:none;marker-mid:none;marker-end:none;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1;visibility:visible;display:inline;overflow:visible"
                 id="path26871" />
              <path
                 d="M 379.92823,489.70212 C 387.842,489.70212 387.842,489.70212 387.842,489.70212 L 387.842,497.61589"
                 style="fill:none;fill-rule:evenodd;stroke:black;stroke-width:3;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
                 id="path27759" />
            </g>
        </g>

    </defs>
  </svg>
</iron-iconset-svg>
```

**Comment by gertcuykens** [comment]
Can you make a pink blinking and sound making `!!!-->pending-answer<--!!!` tag please, red was already taken for bugs :D

**Comment by notwaldorf** [comment]
@gertcuykens `pending-response` means that the Polymer teams needs an answer from the person who opened the issue, so that's not a label you would want in this case. :)

I double checked the `iron-iconset-svg`, and there seems to be a `size` attribute exactly for this: https://github.com/PolymerElements/iron-iconset-svg/blob/master/iron-iconset-svg.html#L27. Does that work?

**Comment by gertcuykens** [comment]
lol yes :D

Thank you!
