### ISSUE TITLE
Safari: setting CSS width or height does nothing to set the size of the icon

### ISSUE THREAD

**Issue by peterwmwong** [PolymerElements/iron-icon#3]
http://jsbin.com/noxaju/3/edit

Chrome (above) vs Safar (below)
![screen shot 2015-04-19 at 1 34 23 pm](https://cloud.githubusercontent.com/assets/284734/7220770/57944798-e699-11e4-841a-49ea90f66213.png)

The icon unexpectedly (and differs from 0.5 behavior) takes the size of the nearest positioned parent (as per regular CSS rules)

**Comment by peterwmwong** [comment]
It appears this was introduced with the original 0.8 port: https://github.com/Polymer/core-icon/commit/735313e01e728fb52debd785d4acf2620aecafd7#diff-4a9edf7beb0e373ce4fb7397d82ef04fR64

I'm not sure if the switch to use `flex` instead of good 'ole `display: inline-block` ([0.5 version](https://github.com/Polymer/core-icon/blob/master/core-icon.css#L9)) was intentional...

As I see we can fix this in 2 ways:
1.  Go back to `inline-block`
2. Add vendor prefixes to make Safari happy

**Comment by cdata** [comment]
This has been fixed by @frankiefu - thanks for raising the issue!
