### ISSUE TITLE
bower.json warning

### ISSUE THREAD

**Issue by davidmaxwaterman** [PolymerElements/iron-icon#53]
```
bower iron-icon#*                invalid-meta iron-icon is missing "ignore" entry in bower.json
```

Inconsequential, I think, but it'd be nice to get it fixed - it kind of stands out against the other elements (well, some others also evoke this message, but not many).

**Comment by notwaldorf** [comment]
@rictic -- is this something `tedium` could automagically fix? (I assume there's maybe other elements that lack an ignore? Maybe?)

If not, I can send a PR out in a jiffy.

**Comment by rictic** [comment]
Huh, `ignore` is only recommended in the spec: https://github.com/bower/spec/blob/master/json.md#ignore

That said, yeah this is super easy for tedium to handle, I'll send out a PR in a bit.

**Comment by GeoloeG-IsT** [comment]
already done here: [56](https://github.com/PolymerElements/iron-icon/pull/56)

**Comment by GeoloeG-IsT** [comment]
BTW, fixed multiple missing "ignore" to be merged...

**Comment by rictic** [comment]
Thanks for the cleanup PR! I merged the linked one, but for the other 39 cases where we need this change my vote is that we use an automatic tool like tedium.

I've just sent out a PR to add this check to tedium: https://github.com/PolymerLabs/tedium/pull/5

**Comment by GeoloeG-IsT** [comment]
would be great indeed! :)

**Comment by rictic** [comment]
All elements in the PolymerElements org have been updated with `ignore` bower properties.
