### ISSUE TITLE
Unable to switch between icon and image display

### ISSUE THREAD

**Issue by alberthier** [PolymerElements/iron-icon#61]
See this jsbin: http://jsbin.com/boruva/edit?html,output

I would like to switch between the polymer logo and the 'check' icon using a single `<iron-icon>`
The 'Toggle' button sets/unsets the `icon` and `src` properties

As long as you use the same image type you can change the image as much as you want. But switching from `icon` to `src` doesn't work

PR #48 fixes this issue

**Comment by danbeam** [comment]
/cc @azakus (maintainer) @kevinpschaaf (TL) @tjsavage (PM)

this would be nice for Chrome's UI as well, and PR #48 seems legit.

i was about to file an issue with a similar repro (http://jsfiddle.net/t8na1wop/).

**Comment by dfreedm** [comment]
Fixed with #48
